#!/usr/bin/env bash
set -euo pipefail

# bootstrap-review-code-artifacts.sh
# Create minimal review-code stage artifacts required by check-run-gate-artifacts.

usage() {
  cat <<'USAGE'
bootstrap-review-code-artifacts.sh — scaffold review-code artifacts

Usage:
  bootstrap-review-code-artifacts.sh --session-dir <path> [--force] [--verify]

Options:
  --session-dir <path>  Target session directory
  --force               Overwrite existing artifacts
  --verify              Run review-code artifact gate in strict mode after generation
  -h, --help            Show this help
USAGE
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

SESSION_DIR=""
FORCE=false
VERIFY=false
CREATED_COUNT=0
SKIPPED_COUNT=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --session-dir)
      SESSION_DIR="${2-}"
      [[ -n "$SESSION_DIR" ]] || fail "--session-dir requires a value"
      shift 2
      ;;
    --force)
      FORCE=true
      shift
      ;;
    --verify)
      VERIFY=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown option: $1"
      ;;
  esac
done

[[ -n "$SESSION_DIR" ]] || fail "--session-dir is required"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATE_SCRIPT="$SCRIPT_DIR/check-run-gate-artifacts.sh"
mkdir -p "$SESSION_DIR"

write_file() {
  local output="$1"
  shift
  if [[ -f "$output" && "$FORCE" != true ]]; then
    SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
    return 0
  fi
  cat > "$output" <<EOF
$*
EOF
  CREATED_COUNT=$((CREATED_COUNT + 1))
}

write_slot_file() {
  local output="$1"
  local title="$2"
  write_file "$output" "# Review Slot — ${title}

## Findings
- Pending manual completion.

## Notes
- Generated by \`bootstrap-review-code-artifacts.sh\` as a deterministic scaffold.

<!-- AGENT_COMPLETE -->"
}

write_slot_file "$SESSION_DIR/review-security-code.md" "Security (Code)"
write_slot_file "$SESSION_DIR/review-ux-dx-code.md" "UX/DX (Code)"
write_slot_file "$SESSION_DIR/review-correctness-code.md" "Correctness (Code)"
write_slot_file "$SESSION_DIR/review-architecture-code.md" "Architecture (Code)"
write_slot_file "$SESSION_DIR/review-expert-alpha-code.md" "Expert Alpha (Code)"
write_slot_file "$SESSION_DIR/review-expert-beta-code.md" "Expert Beta (Code)"

write_file "$SESSION_DIR/review-synthesis-code.md" "## Review Synthesis
### Verdict: REVISE

session_log_present: unknown
session_log_lines: 0
session_log_turns: 0
session_log_last_turn: unavailable
session_log_cross_check: pending

## Summary
- Replace this scaffold with the final synthesis before stage closure.

<!-- AGENT_COMPLETE -->"

echo "Generated review-code artifacts in: $SESSION_DIR"
echo "  created: $CREATED_COUNT"
echo "  skipped: $SKIPPED_COUNT"

if [[ "$VERIFY" == true ]]; then
  [[ -x "$GATE_SCRIPT" ]] || fail "gate script missing: $GATE_SCRIPT"
  bash "$GATE_SCRIPT" --stage review-code --session-dir "$SESSION_DIR" --strict
fi
